### ISSUE TITLE
plot_input_tot errors if given sex disaggregated program data

### ISSUE THREAD

**Issue by hillalex** [mrc-ide/first90release#6]
Have not confirmed, but should also check:
* plot_input_tot
* plot_input_totpos
* plot_input_anctot
* plot_input_ancpos

Nb: although we can't easily test the plots themselves, we can add unit tests that simply run these functions with different datafame inputs and ensures they do not error

**Comment by m-maheu-giroux** [comment]
Alex,
what are the names of the variables in the `prgdat` files? Have they changed? I have downloaded the .csv program data template, filed it with information, and tried to run it in R.

Also, I have played with Cote d'Ivoire on Shiny90, and downloading the program file and re-uploading it gives an error "Error: You cannot upload program data for a different country. This file has been ignored." Must have to do with the accent on the o in the country name.

**Comment by m-maheu-giroux** [comment]
Could it be that your data.frame has capitalized the name for the sex variable `Sex` versus `sex`?

**Comment by hillalex** [comment]
I have created this branch with failing smoke tests to illustrate what's going on:
https://github.com/mrc-ide/first90release/pull/7

To see the test failures you can run `devtools::test()` locally or check out the failing travis build here:
https://travis-ci.com/mrc-ide/first90release/builds/98989862
